-- Create database
CREATE DATABASE IF NOT EXISTS "user-account";

-- Create user (if not exists)
CREATE USER IF NOT EXISTS appuser WITH PASSWORD 'P@55Word';

-- Grant privileges on the DB
GRANT ALL PRIVILEGES ON DATABASE "user-account" TO appuser;

\connect "user-account";

-- Create tables
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(10, 2) NOT NULL,
    course VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fees_status VARCHAR(255) CHECK (fees_status IN ('Paid', 'Unpaid', 'Half_paid')),
    name VARCHAR(255) NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON users TO appuser;
GRANT USAGE ON SCHEMA public TO appuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO appuser;
