-- Create database
CREATE DATABASE "user-account";

-- Create user (if not exists)
CREATE USER appuser WITH PASSWORD 'P@55Word';
GRANT ALL PRIVILEGES ON DATABASE "user-account" TO appuser;

\c "user-account";

-- Create tables
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(10, 2) NOT NULL,
    course VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    fees_status VARCHAR(255) CHECK (fees_status IN ('Paid', 'Unpaid', 'Half_paid')),
    name VARCHAR(255) NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON users TO appuser;
GRANT USAGE ON SCHEMA public TO appuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO appuser;

-- Insert dummy Data
INSERT INTO users (amount, course, email, fees_status, name) VALUES
(5000.00, 'DevOps', 'venkatesh@example.com', 'Paid', 'Venkatesh'),
(4800.00, 'Java', 'chaitanya@example.com', 'Unpaid', 'Chaitanya'),
(5200.00, 'Python', 'padol@example.com', 'Paid', 'Padol'),
(4500.00, 'Testing', 'ganesh@example.com', 'Unpaid', 'Ganesh'),
(7000.00, 'Management', 'pandu@example.com', 'Unpaid', 'Pandu');

SELECT * FROM users;
